export type DocsSearchItem = {
  type: "guide" | "api" | "section";
  title: string;
  description: string;
  href: string;
  params?: Record<string, string>;
  hash?: string;
  keywords: string;
};

export const DOCS_SEARCH_DATA: DocsSearchItem[] = [
  // ── Guide articles (top-level) ─────────────────────────────────────
  {
    type: "guide",
    title: "Quickstart",
    description: "Go from zero to a delivered email in under 60 seconds.",
    href: "/docs/$slug",
    params: { slug: "quickstart" },
    keywords: "getting started first email install npm setup",
  },
  {
    type: "guide",
    title: "Authentication",
    description: "API key creation, scopes, bearer tokens, and revocation.",
    href: "/docs/$slug",
    params: { slug: "authentication" },
    keywords: "api key bearer basic auth scopes permissions",
  },
  {
    type: "guide",
    title: "Sending Email",
    description: "Send transactional emails via REST API or SDKs.",
    href: "/docs/$slug",
    params: { slug: "sending-email" },
    keywords: "send email transactional batch scheduled attachments",
  },
  {
    type: "guide",
    title: "Domains",
    description: "Verify domain ownership via DNS - DKIM, SPF, DMARC.",
    href: "/docs/$slug",
    params: { slug: "domains" },
    keywords: "domain dns dkim spf dmarc mail from verify cname txt",
  },
  {
    type: "guide",
    title: "Webhooks",
    description: "Receive real-time notifications for email events.",
    href: "/docs/$slug",
    params: { slug: "webhooks" },
    keywords: "webhook events delivery bounce open click hmac signature",
  },
  {
    type: "guide",
    title: "CLI",
    description: "Manage domains, send test emails, and tail logs from the terminal.",
    href: "/docs/$slug",
    params: { slug: "cli" },
    keywords: "cli command line terminal postly init logs migrate",
  },

  // ── Quickstart sections ────────────────────────────────────────────
  {
    type: "section",
    title: "Quickstart - Install",
    description: "Install the Node SDK from npm.",
    href: "/docs/$slug",
    params: { slug: "quickstart" },
    hash: "install",
    keywords: "npm install sdk node",
  },
  {
    type: "section",
    title: "Quickstart - Set your API key",
    description: "Create a key in the dashboard and export it.",
    href: "/docs/$slug",
    params: { slug: "quickstart" },
    hash: "set-your-api-key",
    keywords: "api key export environment variable",
  },
  {
    type: "section",
    title: "Quickstart - Send your first email",
    description: "Authenticate and send a transactional email.",
    href: "/docs/$slug",
    params: { slug: "quickstart" },
    hash: "send-your-first-email",
    keywords: "send email first postly.emails.send",
  },
  {
    type: "section",
    title: "Quickstart - Next steps",
    description: "Verify domain, set up webhooks, install CLI.",
    href: "/docs/$slug",
    params: { slug: "quickstart" },
    hash: "next-steps",
    keywords: "next steps domain webhooks cli",
  },

  // ── Authentication sections ────────────────────────────────────────
  {
    type: "section",
    title: "Authentication - Creating an API key",
    description: "Navigate to Settings, name the key, and select scopes.",
    href: "/docs/$slug",
    params: { slug: "authentication" },
    hash: "creating-an-api-key",
    keywords: "create api key scopes dashboard settings",
  },
  {
    type: "section",
    title: "Authentication - Using the key",
    description: "Pass the key as HTTP Basic auth or Bearer token.",
    href: "/docs/$slug",
    params: { slug: "authentication" },
    hash: "using-the-key",
    keywords: "basic auth bearer token curl header authorization",
  },
  {
    type: "section",
    title: "Authentication - Scopes",
    description: "send, read, admin - key permission levels.",
    href: "/docs/$slug",
    params: { slug: "authentication" },
    hash: "scopes",
    keywords: "scopes send read admin permissions",
  },
  {
    type: "section",
    title: "Authentication - Revoking keys",
    description: "Revoked keys stop working immediately with no undo.",
    href: "/docs/$slug",
    params: { slug: "authentication" },
    hash: "revoking-keys",
    keywords: "revoke delete api key",
  },

  // ── Sending Email sections ─────────────────────────────────────────
  {
    type: "section",
    title: "Sending Email - Single send",
    description: "POST to /v1/emails with from, to, subject, and html.",
    href: "/docs/$slug",
    params: { slug: "sending-email" },
    hash: "single-send",
    keywords: "single send post v1 emails from to subject html",
  },
  {
    type: "section",
    title: "Sending Email - Idempotency",
    description: "Prevent duplicate sends with Idempotency-Key header.",
    href: "/docs/$slug",
    params: { slug: "sending-email" },
    hash: "idempotency",
    keywords: "idempotency key duplicate prevent header",
  },
  {
    type: "section",
    title: "Sending Email - Attachments",
    description: "Pass an attachments array with filename and base64 content.",
    href: "/docs/$slug",
    params: { slug: "sending-email" },
    hash: "attachments",
    keywords: "attachments file base64 content type",
  },
  {
    type: "section",
    title: "Sending Email - Rate limits",
    description: "100 req/s for pay-as-you-go, 10 req/s for free tier.",
    href: "/docs/$slug",
    params: { slug: "sending-email" },
    hash: "rate-limits",
    keywords: "rate limit throttle requests per second",
  },

  // ── Domains sections ───────────────────────────────────────────────
  {
    type: "section",
    title: "Domains - Add a domain",
    description: "Use the dashboard or API to add a domain and get DNS records.",
    href: "/docs/$slug",
    params: { slug: "domains" },
    hash: "add-a-domain",
    keywords: "add domain cname dkim spf dmarc dns",
  },
  {
    type: "section",
    title: "Domains - DNS records",
    description: "Add CNAME, TXT, and MX records shown in the dashboard.",
    href: "/docs/$slug",
    params: { slug: "domains" },
    hash: "dns-records",
    keywords: "dns records cname txt mx provider verification",
  },
  {
    type: "section",
    title: "Domains - MAIL FROM",
    description: "Set up a custom MAIL FROM subdomain for better deliverability.",
    href: "/docs/$slug",
    params: { slug: "domains" },
    hash: "mail-from",
    keywords: "mail from subdomain mx spf deliverability",
  },
  {
    type: "section",
    title: "Domains - Verify",
    description: "Check all DNS record types (DKIM, SPF, DMARC) at once.",
    href: "/docs/$slug",
    params: { slug: "domains" },
    hash: "verify",
    keywords: "verify dns check dkim spf dmarc",
  },

  // ── Webhooks sections ──────────────────────────────────────────────
  {
    type: "section",
    title: "Webhooks - Subscribing",
    description: "Create a webhook endpoint and select events to receive.",
    href: "/docs/$slug",
    params: { slug: "webhooks" },
    hash: "subscribing",
    keywords: "subscribe webhook endpoint events create",
  },
  {
    type: "section",
    title: "Webhooks - Event types",
    description: "queued, sent, delivered, bounced, complained, opened, clicked.",
    href: "/docs/$slug",
    params: { slug: "webhooks" },
    hash: "event-types",
    keywords: "event types queued sent delivered bounced complained opened clicked",
  },
  {
    type: "section",
    title: "Webhooks - Signature verification",
    description: "Verify X-Postly-Signature using HMAC-SHA256.",
    href: "/docs/$slug",
    params: { slug: "webhooks" },
    hash: "signature-verification",
    keywords: "signature hmac sha256 verify webhook secret",
  },
  {
    type: "section",
    title: "Webhooks - Retries",
    description: "Failed deliveries retried 6 times over 32 hours.",
    href: "/docs/$slug",
    params: { slug: "webhooks" },
    hash: "retries",
    keywords: "retries exponential backoff failed delivery",
  },

  // ── CLI sections ───────────────────────────────────────────────────
  {
    type: "section",
    title: "CLI - Install",
    description: "Install globally via npm.",
    href: "/docs/$slug",
    params: { slug: "cli" },
    hash: "install",
    keywords: "install cli npm global",
  },
  {
    type: "section",
    title: "CLI - Setup",
    description: "Initialize a project and configure your API key.",
    href: "/docs/$slug",
    params: { slug: "cli" },
    hash: "setup",
    keywords: "setup init configure api key project",
  },
  {
    type: "section",
    title: "CLI - Sending",
    description: "Send a test email from the command line.",
    href: "/docs/$slug",
    params: { slug: "cli" },
    hash: "sending",
    keywords: "send test email command line terminal",
  },
  {
    type: "section",
    title: "CLI - Live logs",
    description: "Stream delivery events in real time.",
    href: "/docs/$slug",
    params: { slug: "cli" },
    hash: "live-logs",
    keywords: "logs tail stream events real time",
  },
  {
    type: "section",
    title: "CLI - Migration",
    description: "Import domains, API keys, and templates from another provider.",
    href: "/docs/$slug",
    params: { slug: "cli" },
    hash: "migration",
    keywords: "migrate import resend provider domains keys templates",
  },

  // ── Docs index section cards ───────────────────────────────────────
  {
    type: "section",
    title: "Getting Started",
    description: "Quickstart, authentication, first send, SDKs.",
    href: "/docs",
    keywords: "getting started quickstart authentication first send sdks",
  },
  {
    type: "section",
    title: "Domains (overview)",
    description: "Add a domain, DKIM / SPF / DMARC, MAIL FROM, Postmaster Tools.",
    href: "/docs",
    keywords: "domains dkim spf dmarc mail from postmaster tools",
  },
  {
    type: "section",
    title: "Sending Email (overview)",
    description: "Single, batch, scheduled, attachments.",
    href: "/docs",
    keywords: "sending email single batch scheduled attachments",
  },
  {
    type: "section",
    title: "Webhooks (overview)",
    description: "Subscribing, HMAC verification, replay, events reference.",
    href: "/docs",
    keywords: "webhooks subscribing hmac verification replay events",
  },
  {
    type: "section",
    title: "CLI (overview)",
    description: "Install, postly init, postly logs, postly migrate.",
    href: "/docs",
    keywords: "cli install init logs migrate terminal",
  },
  {
    type: "section",
    title: "Migration Guides",
    description: "From Resend, Postmark, Lettermint, AhaSend.",
    href: "/docs",
    keywords: "migration resend postmark lettermint ahasend switch provider",
  },
  {
    type: "section",
    title: "Compliance",
    description: "Data residency, DPA, subprocessors, security.",
    href: "/docs",
    keywords: "compliance gdpr data residency dpa subprocessors security",
  },
  {
    type: "section",
    title: "API Reference (overview)",
    description: "Emails, domains, webhooks, templates API reference.",
    href: "/docs/api-reference",
    keywords: "api reference rest endpoints",
  },

  // ── API Reference: Emails ──────────────────────────────────────────
  {
    type: "api",
    title: "POST /v1/emails",
    description: "Send a transactional email.",
    href: "/docs/api-reference",
    hash: "emails",
    keywords: "send email post create transactional message",
  },
  {
    type: "api",
    title: "GET /v1/emails",
    description: "List sent emails with cursor-based pagination.",
    href: "/docs/api-reference",
    hash: "emails",
    keywords: "list emails messages pagination cursor",
  },
  {
    type: "api",
    title: "GET /v1/emails/:id",
    description: "Retrieve a single email with its full event timeline.",
    href: "/docs/api-reference",
    hash: "emails",
    keywords: "get email detail status events timeline",
  },

  // ── API Reference: Domains ─────────────────────────────────────────
  {
    type: "api",
    title: "POST /v1/domains",
    description: "Add a domain and get DNS records to configure.",
    href: "/docs/api-reference",
    hash: "domains",
    keywords: "add create domain dns dkim spf dmarc",
  },
  {
    type: "api",
    title: "GET /v1/domains",
    description: "List all domains in your workspace.",
    href: "/docs/api-reference",
    hash: "domains",
    keywords: "list domains workspace",
  },
  {
    type: "api",
    title: "GET /v1/domains/:domain",
    description: "Get details for a single domain including DNS records.",
    href: "/docs/api-reference",
    hash: "domains",
    keywords: "get domain detail dns records verification status",
  },
  {
    type: "api",
    title: "POST /v1/domains/:domain/verify",
    description: "Trigger a DNS verification check for DKIM, SPF, and DMARC.",
    href: "/docs/api-reference",
    hash: "domains",
    keywords: "verify domain dns check dkim spf dmarc",
  },
  {
    type: "api",
    title: "DELETE /v1/domains/:domain",
    description: "Delete a domain.",
    href: "/docs/api-reference",
    hash: "domains",
    keywords: "delete remove domain",
  },

  // ── API Reference: Suppressions ────────────────────────────────────
  {
    type: "api",
    title: "GET /v1/suppressions",
    description: "List suppressed email addresses with optional reason filter.",
    href: "/docs/api-reference",
    hash: "suppressions",
    keywords: "list suppressions bounce complaint manual unsubscribe",
  },
  {
    type: "api",
    title: "POST /v1/suppressions",
    description: "Manually add an address to the suppression list.",
    href: "/docs/api-reference",
    hash: "suppressions",
    keywords: "add suppress address block manual",
  },
  {
    type: "api",
    title: "DELETE /v1/suppressions/:address",
    description: "Remove an address from the suppression list.",
    href: "/docs/api-reference",
    hash: "suppressions",
    keywords: "delete remove unsuppress address",
  },

  // ── API Reference: API Keys ────────────────────────────────────────
  {
    type: "api",
    title: "POST /v1/api-keys",
    description: "Create a new API key with scoped permissions.",
    href: "/docs/api-reference",
    hash: "api-keys",
    keywords: "create api key scopes permissions",
  },
  {
    type: "api",
    title: "GET /v1/api-keys",
    description: "List all active (non-revoked) API keys.",
    href: "/docs/api-reference",
    hash: "api-keys",
    keywords: "list api keys active",
  },
  {
    type: "api",
    title: "DELETE /v1/api-keys/:id",
    description: "Revoke an API key immediately.",
    href: "/docs/api-reference",
    hash: "api-keys",
    keywords: "delete revoke api key",
  },

  // ── API Reference: Webhooks ────────────────────────────────────────
  {
    type: "api",
    title: "POST /v1/webhooks",
    description: "Register a webhook endpoint with a signing secret.",
    href: "/docs/api-reference",
    hash: "webhooks",
    keywords: "create register webhook endpoint secret events",
  },
  {
    type: "api",
    title: "GET /v1/webhooks",
    description: "List all webhook endpoints.",
    href: "/docs/api-reference",
    hash: "webhooks",
    keywords: "list webhooks endpoints",
  },
  {
    type: "api",
    title: "DELETE /v1/webhooks/:id",
    description: "Delete a webhook endpoint.",
    href: "/docs/api-reference",
    hash: "webhooks",
    keywords: "delete remove webhook endpoint",
  },

  // ── API Reference: Templates ───────────────────────────────────────
  {
    type: "api",
    title: "POST /v1/templates",
    description: "Create a template with its first version.",
    href: "/docs/api-reference",
    hash: "templates",
    keywords: "create template html mjml react slug version",
  },
  {
    type: "api",
    title: "POST /v1/templates/:slug/versions",
    description: "Publish a new version of an existing template.",
    href: "/docs/api-reference",
    hash: "templates",
    keywords: "version template update publish new",
  },
  {
    type: "api",
    title: "GET /v1/templates",
    description: "List all templates.",
    href: "/docs/api-reference",
    hash: "templates",
    keywords: "list templates",
  },
  {
    type: "api",
    title: "GET /v1/templates/:slug",
    description: "Get a template by slug including the current version.",
    href: "/docs/api-reference",
    hash: "templates",
    keywords: "get template slug version detail",
  },
  {
    type: "api",
    title: "DELETE /v1/templates/:slug",
    description: "Delete a template and all its versions.",
    href: "/docs/api-reference",
    hash: "templates",
    keywords: "delete remove template versions",
  },

  // ── API Reference: Account ─────────────────────────────────────────
  {
    type: "api",
    title: "GET /v1/account",
    description: "Get workspace details, plan, and credit balance.",
    href: "/docs/api-reference",
    hash: "account",
    keywords: "account workspace plan credits balance",
  },
];
