/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R2faSetupRouteImport } from './routes/2fa-setup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as LegalPageRouteImport } from './routes/legal.$page'
import { Route as DocsApiReferenceRouteImport } from './routes/docs.api-reference'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as CompareVendorRouteImport } from './routes/compare.$vendor'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AppWebhooksRouteImport } from './routes/app.webhooks'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppSuppressionsRouteImport } from './routes/app.suppressions'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppLogsRouteImport } from './routes/app.logs'
import { Route as AppDomainsRouteImport } from './routes/app.domains'
import { Route as AppDeliverabilityRouteImport } from './routes/app.deliverability'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppApiKeysRouteImport } from './routes/app.api-keys'
import { Route as AppWebhooksIndexRouteImport } from './routes/app.webhooks.index'
import { Route as AppTemplatesIndexRouteImport } from './routes/app.templates.index'
import { Route as AppDomainsIndexRouteImport } from './routes/app.domains.index'
import { Route as AppBillingIndexRouteImport } from './routes/app.billing.index'
import { Route as AppWebhooksIdRouteImport } from './routes/app.webhooks.$id'
import { Route as AppTemplatesSlugRouteImport } from './routes/app.templates.$slug'
import { Route as AppSettingsTeamRouteImport } from './routes/app.settings.team'
import { Route as AppSettingsSecurityRouteImport } from './routes/app.settings.security'
import { Route as AppSettingsAccountRouteImport } from './routes/app.settings.account'
import { Route as AppDomainsDomainRouteImport } from './routes/app.domains.$domain'
import { Route as AppBillingInvoicesRouteImport } from './routes/app.billing.invoices'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R2faSetupRoute = R2faSetupRouteImport.update({
  id: '/2fa-setup',
  path: '/2fa-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LegalPageRoute = LegalPageRouteImport.update({
  id: '/legal/$page',
  path: '/legal/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiReferenceRoute = DocsApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const CompareVendorRoute = CompareVendorRouteImport.update({
  id: '/compare/$vendor',
  path: '/compare/$vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppressionsRoute = AppSuppressionsRouteImport.update({
  id: '/suppressions',
  path: '/suppressions',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsRoute = AppDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliverabilityRoute = AppDeliverabilityRouteImport.update({
  id: '/deliverability',
  path: '/deliverability',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksIndexRoute = AppWebhooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWebhooksRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTemplatesRoute,
} as any)
const AppDomainsIndexRoute = AppDomainsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDomainsRoute,
} as any)
const AppBillingIndexRoute = AppBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppWebhooksIdRoute = AppWebhooksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppWebhooksRoute,
} as any)
const AppTemplatesSlugRoute = AppTemplatesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppTemplatesRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsDomainRoute = AppDomainsDomainRouteImport.update({
  id: '/$domain',
  path: '/$domain',
  getParentRoute: () => AppDomainsRoute,
} as any)
const AppBillingInvoicesRoute = AppBillingInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppBillingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/2fa-setup': typeof R2faSetupRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/billing': typeof AppBillingRouteWithChildren
  '/app/deliverability': typeof AppDeliverabilityRoute
  '/app/domains': typeof AppDomainsRouteWithChildren
  '/app/logs': typeof AppLogsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/suppressions': typeof AppSuppressionsRoute
  '/app/templates': typeof AppTemplatesRouteWithChildren
  '/app/webhooks': typeof AppWebhooksRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$vendor': typeof CompareVendorRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/legal/$page': typeof LegalPageRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/app/billing/invoices': typeof AppBillingInvoicesRoute
  '/app/domains/$domain': typeof AppDomainsDomainRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/settings/team': typeof AppSettingsTeamRoute
  '/app/templates/$slug': typeof AppTemplatesSlugRoute
  '/app/webhooks/$id': typeof AppWebhooksIdRoute
  '/app/billing/': typeof AppBillingIndexRoute
  '/app/domains/': typeof AppDomainsIndexRoute
  '/app/templates/': typeof AppTemplatesIndexRoute
  '/app/webhooks/': typeof AppWebhooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/2fa-setup': typeof R2faSetupRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/deliverability': typeof AppDeliverabilityRoute
  '/app/logs': typeof AppLogsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/suppressions': typeof AppSuppressionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$vendor': typeof CompareVendorRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/legal/$page': typeof LegalPageRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/app/billing/invoices': typeof AppBillingInvoicesRoute
  '/app/domains/$domain': typeof AppDomainsDomainRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/settings/team': typeof AppSettingsTeamRoute
  '/app/templates/$slug': typeof AppTemplatesSlugRoute
  '/app/webhooks/$id': typeof AppWebhooksIdRoute
  '/app/billing': typeof AppBillingIndexRoute
  '/app/domains': typeof AppDomainsIndexRoute
  '/app/templates': typeof AppTemplatesIndexRoute
  '/app/webhooks': typeof AppWebhooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/2fa-setup': typeof R2faSetupRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/billing': typeof AppBillingRouteWithChildren
  '/app/deliverability': typeof AppDeliverabilityRoute
  '/app/domains': typeof AppDomainsRouteWithChildren
  '/app/logs': typeof AppLogsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/suppressions': typeof AppSuppressionsRoute
  '/app/templates': typeof AppTemplatesRouteWithChildren
  '/app/webhooks': typeof AppWebhooksRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$vendor': typeof CompareVendorRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/legal/$page': typeof LegalPageRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/app/billing/invoices': typeof AppBillingInvoicesRoute
  '/app/domains/$domain': typeof AppDomainsDomainRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/settings/team': typeof AppSettingsTeamRoute
  '/app/templates/$slug': typeof AppTemplatesSlugRoute
  '/app/webhooks/$id': typeof AppWebhooksIdRoute
  '/app/billing/': typeof AppBillingIndexRoute
  '/app/domains/': typeof AppDomainsIndexRoute
  '/app/templates/': typeof AppTemplatesIndexRoute
  '/app/webhooks/': typeof AppWebhooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/2fa-setup'
    | '/about'
    | '/app'
    | '/blog'
    | '/changelog'
    | '/contact'
    | '/customers'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/product'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/status'
    | '/verify-email'
    | '/app/api-keys'
    | '/app/billing'
    | '/app/deliverability'
    | '/app/domains'
    | '/app/logs'
    | '/app/messages'
    | '/app/suppressions'
    | '/app/templates'
    | '/app/webhooks'
    | '/blog/$slug'
    | '/compare/$vendor'
    | '/docs/$slug'
    | '/docs/api-reference'
    | '/legal/$page'
    | '/app/'
    | '/blog/'
    | '/docs/'
    | '/app/billing/invoices'
    | '/app/domains/$domain'
    | '/app/settings/account'
    | '/app/settings/security'
    | '/app/settings/team'
    | '/app/templates/$slug'
    | '/app/webhooks/$id'
    | '/app/billing/'
    | '/app/domains/'
    | '/app/templates/'
    | '/app/webhooks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/2fa-setup'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/customers'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/product'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/status'
    | '/verify-email'
    | '/app/api-keys'
    | '/app/deliverability'
    | '/app/logs'
    | '/app/messages'
    | '/app/suppressions'
    | '/blog/$slug'
    | '/compare/$vendor'
    | '/docs/$slug'
    | '/docs/api-reference'
    | '/legal/$page'
    | '/app'
    | '/blog'
    | '/docs'
    | '/app/billing/invoices'
    | '/app/domains/$domain'
    | '/app/settings/account'
    | '/app/settings/security'
    | '/app/settings/team'
    | '/app/templates/$slug'
    | '/app/webhooks/$id'
    | '/app/billing'
    | '/app/domains'
    | '/app/templates'
    | '/app/webhooks'
  id:
    | '__root__'
    | '/'
    | '/2fa-setup'
    | '/about'
    | '/app'
    | '/blog'
    | '/changelog'
    | '/contact'
    | '/customers'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/product'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/status'
    | '/verify-email'
    | '/app/api-keys'
    | '/app/billing'
    | '/app/deliverability'
    | '/app/domains'
    | '/app/logs'
    | '/app/messages'
    | '/app/suppressions'
    | '/app/templates'
    | '/app/webhooks'
    | '/blog/$slug'
    | '/compare/$vendor'
    | '/docs/$slug'
    | '/docs/api-reference'
    | '/legal/$page'
    | '/app/'
    | '/blog/'
    | '/docs/'
    | '/app/billing/invoices'
    | '/app/domains/$domain'
    | '/app/settings/account'
    | '/app/settings/security'
    | '/app/settings/team'
    | '/app/templates/$slug'
    | '/app/webhooks/$id'
    | '/app/billing/'
    | '/app/domains/'
    | '/app/templates/'
    | '/app/webhooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R2faSetupRoute: typeof R2faSetupRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  CustomersRoute: typeof CustomersRoute
  DocsRoute: typeof DocsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  StatusRoute: typeof StatusRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  CompareVendorRoute: typeof CompareVendorRoute
  LegalPageRoute: typeof LegalPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2fa-setup': {
      id: '/2fa-setup'
      path: '/2fa-setup'
      fullPath: '/2fa-setup'
      preLoaderRoute: typeof R2faSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/legal/$page': {
      id: '/legal/$page'
      path: '/legal/$page'
      fullPath: '/legal/$page'
      preLoaderRoute: typeof LegalPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api-reference': {
      id: '/docs/api-reference'
      path: '/api-reference'
      fullPath: '/docs/api-reference'
      preLoaderRoute: typeof DocsApiReferenceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/compare/$vendor': {
      id: '/compare/$vendor'
      path: '/compare/$vendor'
      fullPath: '/compare/$vendor'
      preLoaderRoute: typeof CompareVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/app/webhooks': {
      id: '/app/webhooks'
      path: '/webhooks'
      fullPath: '/app/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppressions': {
      id: '/app/suppressions'
      path: '/suppressions'
      fullPath: '/app/suppressions'
      preLoaderRoute: typeof AppSuppressionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/domains': {
      id: '/app/domains'
      path: '/domains'
      fullPath: '/app/domains'
      preLoaderRoute: typeof AppDomainsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deliverability': {
      id: '/app/deliverability'
      path: '/deliverability'
      fullPath: '/app/deliverability'
      preLoaderRoute: typeof AppDeliverabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/api-keys': {
      id: '/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/webhooks/': {
      id: '/app/webhooks/'
      path: '/'
      fullPath: '/app/webhooks/'
      preLoaderRoute: typeof AppWebhooksIndexRouteImport
      parentRoute: typeof AppWebhooksRoute
    }
    '/app/templates/': {
      id: '/app/templates/'
      path: '/'
      fullPath: '/app/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppTemplatesRoute
    }
    '/app/domains/': {
      id: '/app/domains/'
      path: '/'
      fullPath: '/app/domains/'
      preLoaderRoute: typeof AppDomainsIndexRouteImport
      parentRoute: typeof AppDomainsRoute
    }
    '/app/billing/': {
      id: '/app/billing/'
      path: '/'
      fullPath: '/app/billing/'
      preLoaderRoute: typeof AppBillingIndexRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/app/webhooks/$id': {
      id: '/app/webhooks/$id'
      path: '/$id'
      fullPath: '/app/webhooks/$id'
      preLoaderRoute: typeof AppWebhooksIdRouteImport
      parentRoute: typeof AppWebhooksRoute
    }
    '/app/templates/$slug': {
      id: '/app/templates/$slug'
      path: '/$slug'
      fullPath: '/app/templates/$slug'
      preLoaderRoute: typeof AppTemplatesSlugRouteImport
      parentRoute: typeof AppTemplatesRoute
    }
    '/app/settings/team': {
      id: '/app/settings/team'
      path: '/settings/team'
      fullPath: '/app/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/security': {
      id: '/app/settings/security'
      path: '/settings/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/account': {
      id: '/app/settings/account'
      path: '/settings/account'
      fullPath: '/app/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/domains/$domain': {
      id: '/app/domains/$domain'
      path: '/$domain'
      fullPath: '/app/domains/$domain'
      preLoaderRoute: typeof AppDomainsDomainRouteImport
      parentRoute: typeof AppDomainsRoute
    }
    '/app/billing/invoices': {
      id: '/app/billing/invoices'
      path: '/invoices'
      fullPath: '/app/billing/invoices'
      preLoaderRoute: typeof AppBillingInvoicesRouteImport
      parentRoute: typeof AppBillingRoute
    }
  }
}

interface AppBillingRouteChildren {
  AppBillingInvoicesRoute: typeof AppBillingInvoicesRoute
  AppBillingIndexRoute: typeof AppBillingIndexRoute
}

const AppBillingRouteChildren: AppBillingRouteChildren = {
  AppBillingInvoicesRoute: AppBillingInvoicesRoute,
  AppBillingIndexRoute: AppBillingIndexRoute,
}

const AppBillingRouteWithChildren = AppBillingRoute._addFileChildren(
  AppBillingRouteChildren,
)

interface AppDomainsRouteChildren {
  AppDomainsDomainRoute: typeof AppDomainsDomainRoute
  AppDomainsIndexRoute: typeof AppDomainsIndexRoute
}

const AppDomainsRouteChildren: AppDomainsRouteChildren = {
  AppDomainsDomainRoute: AppDomainsDomainRoute,
  AppDomainsIndexRoute: AppDomainsIndexRoute,
}

const AppDomainsRouteWithChildren = AppDomainsRoute._addFileChildren(
  AppDomainsRouteChildren,
)

interface AppTemplatesRouteChildren {
  AppTemplatesSlugRoute: typeof AppTemplatesSlugRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
}

const AppTemplatesRouteChildren: AppTemplatesRouteChildren = {
  AppTemplatesSlugRoute: AppTemplatesSlugRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
}

const AppTemplatesRouteWithChildren = AppTemplatesRoute._addFileChildren(
  AppTemplatesRouteChildren,
)

interface AppWebhooksRouteChildren {
  AppWebhooksIdRoute: typeof AppWebhooksIdRoute
  AppWebhooksIndexRoute: typeof AppWebhooksIndexRoute
}

const AppWebhooksRouteChildren: AppWebhooksRouteChildren = {
  AppWebhooksIdRoute: AppWebhooksIdRoute,
  AppWebhooksIndexRoute: AppWebhooksIndexRoute,
}

const AppWebhooksRouteWithChildren = AppWebhooksRoute._addFileChildren(
  AppWebhooksRouteChildren,
)

interface AppRouteChildren {
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppBillingRoute: typeof AppBillingRouteWithChildren
  AppDeliverabilityRoute: typeof AppDeliverabilityRoute
  AppDomainsRoute: typeof AppDomainsRouteWithChildren
  AppLogsRoute: typeof AppLogsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppSuppressionsRoute: typeof AppSuppressionsRoute
  AppTemplatesRoute: typeof AppTemplatesRouteWithChildren
  AppWebhooksRoute: typeof AppWebhooksRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiKeysRoute: AppApiKeysRoute,
  AppBillingRoute: AppBillingRouteWithChildren,
  AppDeliverabilityRoute: AppDeliverabilityRoute,
  AppDomainsRoute: AppDomainsRouteWithChildren,
  AppLogsRoute: AppLogsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppSuppressionsRoute: AppSuppressionsRoute,
  AppTemplatesRoute: AppTemplatesRouteWithChildren,
  AppWebhooksRoute: AppWebhooksRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsApiReferenceRoute: typeof DocsApiReferenceRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsApiReferenceRoute: DocsApiReferenceRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R2faSetupRoute: R2faSetupRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  CustomersRoute: CustomersRoute,
  DocsRoute: DocsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  StatusRoute: StatusRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  CompareVendorRoute: CompareVendorRoute,
  LegalPageRoute: LegalPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
